<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WoG.Host\WoG.Host.csproj" />
    <ProjectReference Include="..\..\src\WoG.Headless\WoG.Headless.csproj" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="8.0.1" />
  </ItemGroup>
</Project>
