<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\WoG.Core\WoG.Core.csproj" />
    <ProjectReference Include="..\..\src\WoG.Erm\WoG.Erm.csproj" />
    <ProjectReference Include="..\..\src\WoG.Commanders\WoG.Commanders.csproj" />
    <ProjectReference Include="..\..\src\WoG.CreatureExperience\WoG.CreatureExperience.csproj" />
    <ProjectReference Include="..\..\src\WoG.Host\WoG.Host.csproj" />
    <ProjectReference Include="..\..\src\WoG.Headless\WoG.Headless.csproj" />
    <ProjectReference Include="..\..\src\WoG.OldenEra.Data\WoG.OldenEra.Data.csproj" />
    <ProjectReference Include="..\..\src\WoG.Debug\WoG.Debug.csproj" />
  </ItemGroup>
</Project>
